### ISSUE TITLE
peer review - Luana Capilla

### ISSUE THREAD

**Issue by luana32** [FaustoTenaglia/mercadoLiebre-FaustoTenaglia#1]
Actividad 1- Con respecto a la estructura del sitio: 

HEADER:
 
● Logo **( Contiene )**
● Barra de búsqueda **( Contiene )**
● Comprá en cuotas y sin tarjeta de crédito **( Contiene )**
● Barra de navegación: **( Contiene )**
● Ofertas **( Contiene )**
● Tiendas Oficiales **( Contiene )**
● Vender **( Contiene )**
● Ayuda **( Contiene )**
● Login **( Contiene )**
● Registro **( Contiene )**
● Mis compras **( Contiene )**

MAIN 

● Sección basada en las últimas visitas **( Contiene )**
● Sección de ofertas **( Contiene )**

FOOTER 

● Pagá con tarjeta o en efectivo **( Contiene )**
● Envío gratis desde $ 2.500 **( Contiene )**
● Seguridad, de principio a fin **( Contiene )**
● Copyright © 1999-2022 MercadoLiebre S.R.L. **( Contiene )**

Actividad 2- Estilos (footer)
● ¿El contenido de todos los artículos está centrado?  **(SI)**
● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles? **(SI , TIENE AMBAS)**

Actividad 3- ¿El sitio se adapta a distintas resoluciones de pantalla?
Si se adapta a celulares, tablets y computadoras

Actividad 4- ¿El sitio cuenta con un formulario de registro de usuarios?
Si cuenta con un formulario de registro

Actividad 5- ¿El sitio cuenta con un formulario de login?
Si cuenta con un formulario de login

Actividad 6- ¿Se muestran mensajes de error cuando un usuario coloca información equivocada en un campo de los formularios?
No hay mensaje de error en campos con información errónea

Actividad 7- ¿El search bar es un formulario?
No es un formulario

Actividad 8- ¿Se utilizan animaciones y propiedades de transición de CSS?
Si se usan animaciones y transiciones de CSS

Actividad 9- Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien.
Buen uso de animaciones, transiciones y formato de formularios. Tambien adaptó perfectamente a distintos dispositivos el viewport. Todas las funcionalidades visuales funcionan bien. Tambien se adapta a los requerimientos del cliente 

Actividade 10- Por último, menciona algo que tu compañero podría mejorar.

- Podría mejorar con respecto a los contenedores. Por ejemplo: Poner el footer en un div, luego poner otros 3 div para cada icono con su respectivo texto. Para luego centrar cada div y poniendo el copy fuera, para que quede al final del sitio web

- Tambien recomiendo visitar este sitio web:  https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes 

en la seccion de: Controles de estilo en funcion de si sus datos son validos
Para así poder agregar una validacion de datos en cada formulario

**Comment by RomiPereyar15** [comment]
Actividad 1- Con respecto a la estructura del sitio:

ENCABEZAMIENTO:

● Logo: ✔ 
● Barra de búsqueda: ✔ 
● Comprá en cuotas y sin tarjeta de crédito: ✔ 
● Barra de navegación: ✔ 
● Ofertas: ✔ 
● Tiendas Oficiales: ✔ 
● Vender : ✔ 
● Ayuda : ✔ 


● Iniciar sesión ✔ 
● Registro ✔ 
● Mis compras ✔ 

PRINCIPAL

● Sección basada en las últimas visitas ✔ 
● Sección de ofertas✔ 

PIE DE PÁGINA

● Pagá con tarjeta o en efectivo ✔ 
● Envío gratis desde $ 2.500 ✔ 
● Seguridad, de principio a fin✔ 
● Copyright © 1999-2022 MercadoLiebre SRL✔ 

Actividad 2- Estilos (pie de página)
● ¿El contenido de todos los artículos está centrado? ✔ si
● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles? ✔  tiene ambas
Actividad 3 ¿El sitio se adapta a distintas resoluciones de pantalla? si, se adapta a diversos dispositivos, mejorando la experiencia del usuario.
Actividad 4 ¿El sitio cuenta con un formulario de registro de usuarios?✔ cuenta con un formulario de registro.
Actividad 5 ¿El sitio cuenta con un formulario de inicio de sesión?✔ cuenta con un formulario de inicio de sesión.
Actividad 6 ¿Se muestran mensajes de error cuando un usuario coloca información equivocada en un campo de los formularios? No se muestran mensaje de error.
Actividad 7 ¿La barra de búsqueda es un formulario? No es un formulario.
Actividad 8 ¿Se utilizan animaciones y propiedades de transición de CSS? Si se usan animaciones y transiciones de CSS.
Actividad 9 Para terminar el feedback, menciona algunas cosas que crees que tu compañero hizo bien.  
Al igual que Luana opino que es una pagina web que sobresale bien, diseñada correctamente a lo que el cliente solicito pensando en sus ventas.
